import Header from "@/frontend/Header";
import { AuthProvider } from "./providers";
import { Metadata } from "next";
import Footer from "@/frontend/Footer";
import "bootstrap/dist/css/bootstrap.css";
import "../../public/css/footer.css";
import "../../public/css/header.css";
import "../../public/css/main.css";
import "../../public/css/post.css";
import "../../public/css/home.css";
import "../../public/css/responsive.css";

import ReduxProvider from "@/redux/ReduxProvider";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Find best one",
    template: "%s | Find best one",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Poppins"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <ReduxProvider>
          <AuthProvider>
            <Header />
            {children}
            <Footer />
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
